# JCasC configuration file. Heavily inspired by https://github.com/Praqma/praqma-jenkins-casc
jenkins:
  systemMessage: "Greetings friend! I am a system message configured through JCasC"
  agentProtocols:
    - "JNLP4-connect"
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: insecureAdmin
         password: insecurePassword
  authorizationStrategy:
    globalMatrix:
      grantedPermissions:
        - "Overall/Read:anonymous"
        - "Job/Read:anonymous"
        - "View/Read:anonymous"
        - "Overall/Administer:authenticated"
  crumbIssuer: "standard"
credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              scope: GLOBAL  # this has to be global for scm to work in seed jobs
              id: tholok97_imt3005-project-cicd_deploy-key
              username: tholok97
              passphrase:  ""
              description: "ssh private key used to connect ssh slaves"
              privateKeySource:
                directEntry:
                  # YES. Including a private key in plaintext in VCS is horrible, but did it
                  # for simplicity. See my report for a discussion for possible solutions
                  #
                  # Note that is a Github deploy key, so it only has READ access to ONE
                  # repository, which I'll make public eventually anyways.
                  privateKey: |
                    -----BEGIN RSA PRIVATE KEY-----
                    MIIEowIBAAKCAQEA2fJO47pEqoQkXvoHqyFv5sEfEzENdEAD246rwqGqvfj6TIzA
                    eCflEYWBVK52lauG5LfTKjE2BLyMXWSEFDjMGNUEnFzyKBkQYFy6A1jX5SDUOA8A
                    SAat4Htj3+gOxlwZWmErCL5E+HWBkRZCgL9IBx8TwED+9gc/7q2j4eu5qTdbqLkD
                    vmPlpfBMMZsPwcMSWInwFlQXa/qjwo73MWTWVcbqx5HKn6NcTDlsJFtqkLCZBMGZ
                    THcno97efYZJRpqs6iQidQ4V6BxPt4AUJhLL7Ehb8vxBzHw6gNkKmqNMxoTtmiWb
                    QRPBfDh/nQavs1KLZwUj8jhLIkYeHvDu0a9InQIDAQABAoIBABW4GvqAvoULpCA+
                    5HK+Y0topXMhKUkTdA72OdGskLpbzH3CbQ/MUfycBFZvCGxD6q5yTz3eJ5bzPz2z
                    XaIyQsyatdnrPUqXrNUdiH/645D2448ul4WV/M/pG/vdQVOtK+2gz0wQwgjMlPvj
                    bv8rkL787tfy4jWcZVegwDssZZUiOvt53NFJDk+Bk8++1bCaxup5y3Wrr2Sat1e8
                    KA7/Wzwv5TFxFVZ3qykYpuLm/xFgtbsI8AieWsLsHIkMR1L0XmtwIEF4r0ZfVc5P
                    m9IrkEeYCEorhPaTMQHTMK3/QMlBjJHGdMLgRzje++awaF+qvl72ALfguFG1CvPL
                    0OIHB2ECgYEA+sCAFvUBrw+O4ZOz4jPv8GgO7e2xWbNU/ybsDyaH5JyD6MGmVwPy
                    RUODeQmF681k9spUOUHexzq9/hu1dts4v63v2+ZBQnOEbjoD7gpsnIxr99x/DZOe
                    Vrmpj8y288MdGAUn9BSWF1JumY/ln6pSQLgzK1J72NWXxiD2+zc1gikCgYEA3oIK
                    RKl7UMnkArr2Xpy9ocDJzFx9EdQAs4ZLEpDdF4czgooBSxhrIv+fzbpLcS+RcMVR
                    TpOddRifEzcY+GSS/M3hbHpNU28A2F75ERFJMMeGya4nAMqE7WuImG40hOUNr75X
                    53vxaV0XIIIBJzy8yrbNR7C7ERycSXTBIKXOqVUCgYEAj2IyHG5/Rv5Lgpv2GZv/
                    UOX/23e2mQddzAUSqNssi8If/6F0H3/HMmoXrMeQR7UMTb6GiLMs05m4eKyZiFx0
                    x86LQKAaowfxKyKLirt1PdNiDbqNAFNwEEFcPzkdSKhCY7DXFtAKv01IpxDMig9X
                    t2BdCiHBZc1FW2sQL7hzJXkCgYB7k6F8TNyOG/KkiY23MjonkdkBxQQ5WJMjIZyk
                    LQx9ursi7t6VBHTMNUhdi+/GZvLRvOTRTS6QECKZG2qk2cbA3N8rzikQA4BmqyiN
                    EBqkGsyDSlOjHtcAvU5Zyisk+8nEJ2TOzYlgSTFE/q8BSbxYoXoVLNRYRpmOOmfg
                    Z/YFGQKBgFoNM7fKW6Bn78J64ti5yMLH1HjT4WY5KfDNE6tuUYvW5k8ruFpElwsT
                    Xk9geLe6jva+NwIMAnXqG+JIsI5DX59dHTzHO2NpD8Adc34ht1YsleqwF2TXO9Fq
                    ZkF1yeeuK1gzS3B59a/iHSUGuqy2+A+Ixvke9hsKcCFo3KpRR4bF
                    -----END RSA PRIVATE KEY-----

jobs:
# taken from https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/seed-jobs.md
# and https://marcesher.com/2016/08/04/jenkins-as-code-comparing-job-dsl-and-pipelines/
#
# The following three jobs are just here eto show some examples of job dsl configured through JCasC
  - script: |
      def myJob = freeStyleJob('SimpleJob')
      myJob.with {
          description 'A Simple Job'
      }
  - script: |
      job('example-job-from-job-dsl') {
          scm {
              github('jenkinsci/job-dsl-plugin', 'master')
          }
          triggers {
              cron("@hourly")
          }
          steps {
              shell("echo 'Hello World'")
          }
      }
  - script: |
      pipelineJob("pipeline-calls-other-pipeline") {
                  logRotator{
                      numToKeep 30
                  }
                  definition {
                      cps {
                          sandbox()
                          script("""
                              node {
                                  echo 'Hello World 1'
                              }
                          """.stripIndent())
                          }
                      }
                  }
# The below job sets up a pipeline job for my gossinbackup module. The Jenkinsfile of that module is used.
# Added as a demonstration that jobs work
# Reference used: https://jenkinsci.github.io/job-dsl-plugin/#path/pipelineJob
  - script: |
      pipelineJob("pipeline-job-to-run-gossinbackup") {
                  definition {
                      cpsScm {
                          scm {
                              git('https://github.com/tholok97/gossinbackup', 'master')
                          }
                      }
                  }
      }
# sets up control-repo testing
  - script: |
      pipelineJob("control repo") {
                  definition {
                      cpsScm {
                          scm {
                              git {
                                  remote {
                                      github('tholok97/imt3005-project-cicd', 'ssh')
                                      credentials('tholok97_imt3005-project-cicd_deploy-key')
                                  }
                              }
                          }
                      }
                  }
      }
# These jobs are from the demo I copied this config from. Left in for reference
#  - url: https://raw.githubusercontent.com/Praqma/job-dsl-collection/master/configuration-as-code-dsl/pipeline.dsl #casc
#  - url: https://raw.githubusercontent.com/Praqma/memory-map-plugin/master/jenkins-pipeline/pipeline.groovy #memory map
#  - url: https://raw.githubusercontent.com/Praqma/codesonar-plugin/master/jenkins-pipeline/pipeline.groovy #codesonar
#  - url: https://raw.githubusercontent.com/Praqma/pretested-integration-plugin/master/jenkins-pipeline/pipeline.groovy #pretested integration
#  - url: https://raw.githubusercontent.com/Praqma/ClearCaseUCMPlugin/master/jenkins-pipeline/pipeline.groovy #ccucm
#  - url: https://raw.githubusercontent.com/Praqma/Praqmatic-Automated-Changelog/master/jenkins-pipeline/pipeline.groovy #pac
#  - url: https://raw.githubusercontent.com/Praqma/PlusBump/rebirth/jenkins-pipeline/pipeline.groovy #plusbump
#  - url: https://raw.githubusercontent.com/Praqma/job-dsl-collection/master/web-pipeline-dsl/web_pipeline_dsl.groovy #websites
#  - file: ./jobdsl/rut.groovy #rut (private repo...better keep it here)

tool:
  git:
    installations:
      - name: Default
        home: "git"

security:
  remotingCLI:
    enabled: false
